### ISSUE TITLE
download multiples douj. one after oneother

### ISSUE THREAD

**Issue by dxdvostfr** [nightglimpse/nHentai-Downloader#1]
Could there be a way to automatically download a list of douj. (like mutiple links in a file like this)
![image](https://user-images.githubusercontent.com/49651963/210939560-1e0eb289-d2b5-46ff-8aa2-3b0c8e1a73a5.png)

**Comment by nightglimpse** [comment]
The snippet below makes it possible. If you don't want to bother with the explanations, just copy and paste it. Else, see below.

````
url_file = open(value).read()

url_list = url_file.split("\n")

for url in url_list:
    doujin_id, page_list = parse_url_page(url)
    download_images(doujin_id, page_list) 
    img_to_pdf(download_path = f"{BASEPATH}/{doujin_id}", final_path = BASEPATH, doujin_id = doujin_id)
     
````

What this code does is that it opens the textfile you entered on read mode and using the read() function, convert the bytes into a string. The split() function then converts it into a list of substrings that are before a certain separator, in your case the '\n' value. Then just use a for loop to iterate through the list and that's it!

**Comment by dxdvostfr** [comment]
thanks for replying this fast! 

Where should I put it? I tried some locations but it made the script errored.

**Comment by nightglimpse** [comment]
you can put it under L81 (if__name__ == "__main__":)

**Comment by dxdvostfr** [comment]
Maybe you modified main on your side because the one I have (latest from the repo) only has 70 lines of code

When using it under (if__name__ == "main":) I get an `Traceback (most recent call last):
  File "C:\Users\Neko\Desktop\nHentai-Downloader-master\main.py", line 63, in <module>
    url_file = open(value).read()
                    ^^^^^
NameError: name 'value' is not defined. Did you mean: 'False'?`

**Comment by dxdvostfr** [comment]
Maybe you modified main on your side because the one I have (latest from the repo) only has 70 lines of code

When using it under (if__name__ == "main":),  I get an 

Traceback (most recent call last): File "C:\Users\Neko\Desktop\nHentai-Downloader-master\main.py", line 63, in <module> url_file = open(value).read() 
NameError: name 'value' is not defined. Did you mean: 'False'?

**Comment by nightglimpse** [comment]
My bad. It should be 'url' for you.

**Comment by dxdvostfr** [comment]
url isn't defined either 😭

**Comment by dxdvostfr** [comment]
url isn't defined either 😭

**Comment by nightglimpse** [comment]
Below is the structure I have tested that worked for me. If the issue still occurs, we can continue this discussion on Discord (glimpse#2163).
![image](https://user-images.githubusercontent.com/119710412/210957504-456808eb-c778-4a39-92ae-03a54612e785.png)

**Comment by dxdvostfr** [comment]
works thanks!
